activation_mode: hold
click_mode: fast
clicks_per_second: 10
enable_logging: true
hotkey: shift
input_type: mouse
keyboard_key: a
keyboard_mode: repeat
target_position: null
verbose_mode: false
prevent_idle: false
idle_prevention_interval: 30
randomize_timing: false
randomness_percent: 20.0
