[tool.briefcase]
project_name = "Roblox Autoclicker"
bundle = "com.roblox"
version = "1.5.0"
url = "https://github.com/whaeuser/RobloxAutoclicker"
license = "MIT"
author = "whaeuser"
author_email = "noreply@example.com"

[tool.briefcase.app.robloxautoclicker]
formal_name = "Roblox Autoclicker"
description = "Konfigurierbarer Autoclicker fÃ¼r macOS"
sources = ['autoclicker_gui_toga']
icon = "resources/icon"  # TODO: Icon erstellen
requires = [
    'toga>=0.4.0',
    'pyautogui',
    'pynput',
    'pyyaml',
]

[tool.briefcase.app.robloxautoclicker.macOS]
requires = [
    'toga-cocoa>=0.4.0',
]

[build-system]
requires = ["briefcase"]
